name: Testing

on: [pull_request]

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Install SWI-Prolog backend
        uses: logtalk-actions/setup-swi-prolog@master
        with:
          swi-prolog-branch: stable
          swi-prolog-version: latest
      - name: Install Logtalk
        uses: logtalk-actions/setup-logtalk@master
        with:
          logtalk-version: latest
          logtalk-tool-dependencies: false
      - name: Checkout Logtalk application to be tested
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
      - name: Checkout application dependencies
        uses: actions/checkout@v1
        with:
          repository: PaulBrownMagic/Situations
          ref: refs/heads/master
          fetch-depth: 1
      - name: Run the application tests
        run: |
          echo ":- multifile(logtalk_library_path/2)." > settings.lgt
          echo ":- dynamic(logtalk_library_path/2)." >> settings.lgt
          echo "logtalk_library_path(situations, '/home/runner/work/SitCalc/Situations/')." >> settings.lgt
          logtalk_tester
